# Fictional Army - Filtering and Sorting

> Notebook resuelto con explicaciones paso a paso

### Step 1. Importamos Pandas

Siempre que trabajamos con Pandas, lo primero es importarlo. Por convención se importa con el alias `pd` para no tener que escribir `pandas` cada vez.

In [2]:
import pandas as pd

### Step 2. Datos en forma de diccionario

Los datos ya nos los dan. Un diccionario en Python es una estructura `{clave: valor}`. Aquí cada clave es el nombre de una columna, y cada valor es una lista con los datos de esa columna.

In [3]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Step 3. Crear un DataFrame y asignarlo a la variable `army`

`pd.DataFrame(raw_data)` convierte el diccionario en una tabla (DataFrame). Piénsalo así:
- El **diccionario** tiene claves → esas claves se convierten en los **nombres de las columnas**
- Cada **lista** de valores → se convierte en los **datos de esa columna**
- Pandas automáticamente le asigna un índice numérico (0, 1, 2...) a cada fila

In [4]:
# pd.DataFrame() es la función que convierte cualquier estructura de datos compatible en una tabla
army = pd.DataFrame(raw_data)

# Mostramos las primeras filas para verificar que se creó bien
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Step 4. Poner la columna 'origin' como índice

Por defecto, el índice es numérico (0, 1, 2...). Con `set_index('origin')` le decimos a Pandas:
*"usa la columna origin como las etiquetas de las filas"*.

Esto es útil porque después podremos buscar filas por nombre de estado (ej: `army.loc['Texas']`) en lugar de por número.

**Importante:** `set_index()` no modifica el DataFrame original, devuelve uno nuevo. Por eso reasignamos con `army = army.set_index('origin')`.

In [ ]:
# set_index('origin') convierte la columna 'origin' en el índice del DataFrame
# Es decir, los nombres de los estados pasan a ser las "etiquetas" de las filas
army = army.set_index('origin') # Convertimos army = con la nueva distribución porque si no, con set_index() no modifica el DataFrame original.

army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 5. Mostrar solo la columna 'veterans'

Para seleccionar **una sola columna** de un DataFrame usamos corchetes con el nombre entre comillas: `army['veterans']`

Esto devuelve una **Serie** (no un DataFrame). Una Serie es como una columna individual, con su índice (los nombres de los estados) y sus valores.

In [ ]:
# army['veterans'] -> selecciona la columna llamada 'veterans'
# El resultado es una Serie: una lista de valores con etiquetas (el índice)
army['veterans']

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

### Step 6. Mostrar las columnas 'veterans' y 'deaths'

Para seleccionar **múltiples columnas** pasamos una **lista** de nombres dentro de los corchetes.
Fíjate en el doble corchete: `army[['veterans', 'deaths']]`
- El corchete exterior → le dice a Pandas que vamos a seleccionar columnas
- El corchete interior → es la lista Python con los nombres de las columnas

El resultado ahora sí es un **DataFrame** (tiene más de una columna).

In [7]:
# Doble corchete: army[[lista_de_columnas]]
# El interior es una lista Python ['col1', 'col2']
army[['veterans', 'deaths']]

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

### Step 7. Mostrar el nombre de todas las columnas

El atributo `.columns` de un DataFrame nos devuelve un objeto Index con los nombres de todas las columnas.
No es un método (no lleva paréntesis), es una propiedad del DataFrame.

In [8]:
# .columns es un atributo (propiedad) del DataFrame, no un método
# Devuelve un objeto Index con todos los nombres de columnas
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='str')

### Step 8. Seleccionar columnas 'deaths', 'size' y 'deserters' de Maine y Alaska

Aquí necesitamos seleccionar filas **Y** columnas específicas a la vez. Para eso usamos **`.loc[]`**

`.loc[]` trabaja con **etiquetas** (nombres). Su sintaxis es:
```
army.loc[filas, columnas]
```
- `filas` → lista de etiquetas de fila: `['Maine', 'Alaska']`
- `columnas` → lista de nombres de columna: `['deaths', 'size', 'deserters']`

`.loc` es el selector cuando conoces los **nombres** (etiquetas).

In [9]:
# .loc[filas, columnas] -> selección por ETIQUETAS (nombres)
# Primero le decimos qué filas queremos (por nombre de estado)
# Luego qué columnas queremos (por nombre de columna)
army.loc[['Maine', 'Alaska'], ['deaths', 'size', 'deserters']]

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

### Step 9. Seleccionar filas 3 a 7 y columnas 3 a 6

Aquí seleccionamos por **posición numérica** (número de fila/columna), no por nombre.
Para eso usamos **`.iloc[]`** (la "i" es de "integer").

`.iloc[]` usa la misma lógica de slicing que NumPy: `inicio:fin` donde **el fin no está incluido**.
- `iloc[3:7]` → filas en posición 3, 4, 5, 6 (no la 7)
- `iloc[:, 3:6]` → columnas en posición 3, 4, 5 (no la 6)

**Resumen clave:**
- `.loc[]` → por **nombres/etiquetas**
- `.iloc[]` → por **posición numérica** (0, 1, 2...)

In [ ]:
# .iloc[filas, columnas] -> selección por POSICIÓN (números enteros)
# 3:7 significa posiciones 3, 4, 5, 6 (el 7 no se incluye, igual que en NumPy)
army.iloc[3:7, 3:6]

         battles  size  veterans
origin
Florida        2  1400        26
Maine          4  1592        73
Iowa           7  1006        37
Alaska         8   987       949

### Step 10. Seleccionar todas las filas después de la cuarta y todas las columnas

Con `.iloc` podemos hacer slicing:
- `4:` → desde la posición 4 hasta el final (sin límite superior)
- `:` → todas las columnas (sin límite inferior ni superior)

Es exactamente igual que el slicing de listas en Python: `lista[4:]`

In [11]:
# 4: -> desde la fila en posición 4 hasta el final
# : -> todas las columnas (sin restricción)
army.iloc[4:, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 11. Seleccionar hasta la 4ª fila (incluida) y todas las columnas

- `:4` → desde el inicio hasta la posición 4 (la posición 4 NO se incluye, así que obtenemos 0, 1, 2, 3)
- `:` → todas las columnas

In [13]:
# :4 -> desde el inicio hasta la posición 4 (sin incluir la 4, igual que slicing Python). Si fuese 4 incluido sería :5
# Obtenemos las filas 0, 1, 2, 3 → las primeras 4 filas
army.iloc[:4, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2

### Step 12. Seleccionar desde la columna 3 hasta la 7

Seleccionamos todas las filas (`:`) y las columnas desde la posición 3 hasta la 6 (recordar: 7 no se incluye).

In [14]:
# : -> todas las filas
# 3:7 -> columnas en posición 3, 4, 5, 6
army.iloc[:, 3:7]

            battles  size  veterans  readiness
origin
Arizona           5  1045         1          1
California       42   957         5          2
Texas             2  1099        62          3
Florida           2  1400        26          3
Maine             4  1592        73          2
Iowa              7  1006        37          1
Alaska            8   987       949          2
Washington        3   849        48          3
Oregon            4   973        48          2
Wyoming           7  1005       435          1
Louisana          8  1099        63          2
Georgia           9  1523       345          3

### Step 13. Seleccionar filas donde deaths > 50

Esto es **filtrado booleano** (o "masking"), igual que en NumPy.
Funciona en 2 pasos:
1. `army['deaths'] > 50` → crea una Serie de True/False para cada fila
2. `army[...]` → pasa esa Serie como índice, y Pandas solo devuelve las filas donde es True

Es como decirle a Pandas: *"dame solo las filas donde esta condición es verdadera"*

In [15]:
# Paso 1: army['deaths'] > 50 genera una máscara de True/False
# Paso 2: army[máscara] filtra y devuelve solo las filas donde la condición es True
army[army['deaths'] > 50]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

### Step 14. Seleccionar filas donde deaths > 500 OR deaths < 50

Para combinar múltiples condiciones en Pandas:
- **OR** → se escribe con `|` (tubería/pipe)
- **AND** → se escribe con `&`

**Importante:** Cada condición individual DEBE ir entre paréntesis cuando las combinamos. Sin los paréntesis, Python se confunde con el orden de operaciones.

In [16]:
# | es el operador OR en Pandas (no se usa 'or')
# Cada condición va entre paréntesis obligatoriamente
army[(army['deaths'] > 500) | (army['deaths'] < 50)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 15. Seleccionar todos los regimientos que NO sean "Dragoons"

Para negar una condición usamos `~` (tilde), que es el operador NOT en Pandas.
También podemos usar `!=` (diferente de) para una comparación directa de desigualdad.

In [17]:
# Opción 1: != (diferente de) -> directamente compara que no sea igual a 'Dragoons'
army[army['regiment'] != 'Dragoons']

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

In [19]:
# Opción 2: ~ (tilde? virgulilla?) niega la condición completa
# ~ es el NOT booleano en Pandas (equivale a 'no es verdad que...')
army[~(army['regiment'] == 'Dragoons')]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 16. Seleccionar las filas llamadas Texas y Arizona

Como el índice del DataFrame son los nombres de los estados (lo cambiamos en el Step 4), podemos seleccionar filas por nombre usando `.loc[]`.

Pasamos una lista con los nombres que queremos.

In [21]:
# Como el índice del DataFrame son los nombres de los estados (lo cambiamos en el Step 4), podemos seleccionar filas por nombre usando `.loc[]`.
# .loc con una lista de etiquetas -> devuelve las filas con esos nombres de índice
army.loc[['Texas', 'Arizona']]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

### Step 17. Seleccionar la tercera celda en la fila de Arizona

Necesitamos una fila específica (por nombre) y dentro de ella, una celda específica (por posición).

Podemos combinar `.loc` y `.iloc`:
1. `army.loc['Arizona']` → selecciona la fila de Arizona (devuelve una Serie)
2. `.iloc[2]` → de esa Serie, toma el elemento en posición 2 (la tercera, porque empieza en 0)

**Recuerda:** en Python los índices empiezan en 0: posición 0 = primera, posición 2 = tercera.

In [23]:
# Paso 1: army.loc['Arizona'] -> selecciona la fila Arizona como una Serie
# Paso 2: .iloc[2] -> de esa Serie, toma el elemento en posición 2 (el tercero)
# Posición 0=regiment, 1=company, 2=deaths -> el tercero es 'deaths'
army.loc['Arizona'].iloc[2]

np.int64(523)

### Step 18. Seleccionar la tercera celda hacia abajo en la columna deaths

Ahora al revés: seleccionamos primero la columna (por nombre) y luego una fila (por posición).

1. `army['deaths']` → selecciona la columna deaths (devuelve una Serie)
2. `.iloc[2]` → de esa Serie, toma el elemento en posición 2 (la tercera fila)

In [24]:
# Paso 1: army['deaths'] -> selecciona la columna deaths como una Serie
# Paso 2: .iloc[2] -> de esa columna, toma el valor en la tercera posición (índice 2)
# Eso corresponde a Texas (fila 0=Arizona, 1=California, 2=Texas)
army['deaths'].iloc[2]

np.int64(25)

---
## 📋 Resumen de conceptos clave del ejercicio

| Operación | Sintaxis | Cuándo usarla |
|-----------|----------|---------------|
| Crear DataFrame | `pd.DataFrame(datos)` | Siempre que quieras crear una tabla |
| Cambiar índice | `df.set_index('columna')` | Cuando una columna tiene mejores etiquetas que números |
| Una columna | `df['columna']` | Para seleccionar una columna → devuelve Serie |
| Varias columnas | `df[['col1', 'col2']]` | Para seleccionar varias → devuelve DataFrame |
| Nombres de columnas | `df.columns` | Para ver qué columnas existen |
| Selección por etiqueta | `df.loc[filas, columnas]` | Cuando conoces los **nombres** |
| Selección por posición | `df.iloc[filas, columnas]` | Cuando conoces los **números** |
| Filtrado simple | `df[df['col'] > valor]` | Para filtrar por una condición |
| Filtrado OR | `df[(cond1) \| (cond2)]` | Para filtrar con dos condiciones alternativas |
| Filtrado NOT | `df[~(condicion)]` o `df[df['col'] != valor]` | Para negar una condición |